# Project: ComputerGraphics
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = test.o
LINKOBJ  = test.o
LIBS     = -L"E:/riri/Softwares/Dev-Cpp/MinGW64/lib32" -L"E:/riri/Softwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32 -luser32 -m32
INCS     = -I"E:/riri/Softwares/Dev-Cpp/MinGW64/include" -I"E:/riri/Softwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/riri/Softwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"E:/riri/Softwares/Dev-Cpp/MinGW64/include" -I"E:/riri/Softwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/riri/Softwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/riri/Softwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = ComputerGraphics.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

test.o: test.cpp
	$(CPP) -c test.cpp -o test.o $(CXXFLAGS)
